[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "deb2repo-client"
version = "0.1.0"
description = "Secure CLI and SDK for deb2repo managment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["requests>=2.31.0"]

[project.scripts]
repo-cli = "deb2repo_client.main:main"
