FROM python:3.11-slim

RUN apt-get update && apt-get install -y dpkg-dev gnupg apt-utils --no-install-recommends && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml .
COPY src/ ./src/

RUN pip install --no-cache-dir .

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "deb2repo_server.main:app", "--host", "0.0.0.0", "--port", "8000"]
